# -*- coding: utf-8 -*-
"""
/***************************************************************************
 mLasMedia
                                 A QGIS plugin
 Wtyczka pozwalająca wyświetlić pomiary wyeksportowane za pomocą aplikacji mLas.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-06-15
        copyright            : (C) 2025 by Katarzyna Kucharczyk Taxus IT sp. z o. o.
        email                : katarzyna.kucharczyk@taxusit.pl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load mLasMedia class from file mLasMedia.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .mlasmedia import mLasMedia
    return mLasMedia(iface)
